### ISSUE TITLE
Native Julia implementation

### ISSUE THREAD

**Issue by DNF2** [rurz/WG_FractionalEvolution#1]
In case you aren't aware, you don't need mpmath to implement `nbinom` and `krav`. You can find the `beta` function in SpecialFunctions.jl and the `2F1` function in HypergeometricFunctions.jl. As far as I can tell, this is between 50-1000x faster than calling mpmath through PyCall.

The main drawback is that HypergeometricFunctions.jl seems to be severely lacking in documentation.

**Comment by rurz** [comment]
Hello, thank you for your kindly advice. I didn't know that those libraries exist on Julia, but certainly I will implement and push it as soon as possible, to step-up the calculations speed when the dimension N is considerable. As you fore mention in the title, It is part of my aim to have a native Julia code.
